### ISSUE TITLE
0.25, 0.26, 0.27, 0.28, 0.29, 0.30 mappings

### ISSUE THREAD

**Issue by absolutelyunacceptable** [MCPHackers/MCPHackers.github.io#5]
Hey. Add the mappings for these versions or else.

**Comment by PhoenixVX** [comment]
Or else what? Do you not realize people have lives outside of working on open source projects? Hell... Classic mappings for these versions are complete, but they aren't going to be added to versions V1 so they won't even be usable. Versions V2 which is being worked on for the next version of RetroMCP are where they are going to be added. No offense, but don't use snarky language if you want something done at the behest of others.

**Comment by Lassebq** [comment]
Was that a threat?
